"""nullable name

Revision ID: b8c4b1d61472
Revises: 471ac157647a
Create Date: 2024-08-20 14:01:00.363231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c4b1d61472'
down_revision = '471ac157647a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campers', 'name')
    op.add_column('campers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
